#!/bin/bash

set -eu

stream_test --sshhosts "$(cat /etc/streamtesternodes)" --sshkeyfile /home/ubuntu/.ssh/id_rsa "$@" 2> lastrun.stderr > lastrun.stdout &
testpid="$!"

sleep 0.5

tail -n +0 -f lastrun.stderr >&2 &
tailpid="$!"

trap "kill $tailpid $testpid > /dev/null 2>&1" EXIT

while ps --pid $testpid > /dev/null && [ $(cat lastrun.stdout | wc -c) -eq 0 ]
do
    sleep 1
done

kill $tailpid > /dev/null 2>&1

if [ $(cat lastrun.stdout | wc -c) -ne 0 ]
then
    tail -f lastrun.stdout | display.py
fi
